### Test basic auth
POST http://localhost:8080
Content-Type: application/json

{ "password" : "AGrPrdfU7p"}

### Add Wish
POST localhost:8080/wishes
Content-Type: application/json

{
    "password" : "AGrPrdfU7p",
    "wish": "I want game"
}

### Add Wish 2
POST localhost:8080/wishes
Content-Type: application/json

{
  "password" : "AGrPrdfU7p",
  "wish": "I want game 2"
}

### Swap wishes
POST localhost:8080/swap
Content-Type: application/json

{
  "password" : "AGrPrdfU7p",
  "id1": 0,
  "id2": 1
}

### Get all wishes
GET http://localhost:8080/wishes

